# swagger文档目录(也可以启动服务时使用-swagger指定)
swagger: ''

# http配置
http:
  # http监听地址
  host: 0.0.0.0
  # http监听端口
  port: 8080

# 日志配置
log:
  # 日志级别(ALL, DEBUG, INFO, WARN, ERROR, FATAL, OFF)
  level: 1
  # 日志格式（支持输出格式：text/json）
  format: text
  ## 日志输出(支持：stdout/stderr/file)
  output: "stdout"
  # 指定日志输出的文件路径
  log_file: /var/log/dvs/dvs.log
  # http优雅关闭等待超时时长(单位秒)
  shutdown_timeout: 30
  access_log: /var/log/dvs/access.log

# gorm配置
gorm:
  # 是否开启调试模式
  debug: true
  # 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
  db_type: mysql
  # 设置连接可以重用的最长时间(单位：秒)
  max_lifetime: 7200
  # 设置数据库的最大打开连接数
  max_open_conns: 150
  # 设置空闲连接池中的最大连接数
  max_idle_conns: 50
  # 数据库表名前缀
  table_prefix: "g_"
  # 是否启用自动映射数据库表结构
  enable_auto_migrate: true

# redis配置
redis:
  # 地址
  host: 127.0.0.1:6379
  # 指定库
  db: 0
  # 密码
  password: ""

# mysql数据库配置
mysql:
  # 连接地址
  host: 127.0.0.1
  # 连接端口
  port: 3306
  # 用户名
  user: root
  # 密码
  password: 123456
  # 数据库
  db_name: dvs
  # 连接参数
  parameters: charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true
